### ISSUE TITLE
OPC UA 2017+ on PXI

### ISSUE THREAD

**Issue by Sylphe88** [NIVeriStandAdd-Ons/OPC-UA-Client-Custom-Device#2]
Hey there!

Trick question: how can we run the CD with VeriStand 2017 or 2018, knowing NI changed OPC UA for 2017+, and dropped support for Pharlap. From LV we can still build the CD for Pharlap but it won't deploy because it will not find the right components (the DLLs changed) on the target.

More globally, how can we run a 2017+ OPC client from Pharlap? There must be a way, come on you guys can't drop one of your homemade OS support for a protocol like that.

**Comment by tannerblair** [comment]
@Sylphe88, unfortunately as you noted the driver doesn't support 2017+, so we won't be able to modify this CD to do so either.

Additionally, to set expectations on support, this GitHub organization is a community project, not an NI project. The "you guys" in question might contain some NI employees, but isn't wholly comprised of or affiliated with NI. 

If you find a driver that does support Pharlap for 2017 and 2018 you're welcome to modify the Custom Device to use that instead and create a pull request. In the meantime I'll create an issue to update the documentation to reflect that we can't support 2017+.

**Comment by Sylphe88** [comment]
Hi Tanner,

Sorry for the "you guys", I never intended to rage against AES/SE who mostly maintain this Github org. It's just I don't get the how NI makes such decisions sometimes. The PXI platform probably accounts for half of the NI RT targets, losing a feature like that is a great penalty...
